/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package m2.ejercicio.n.pkg29;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author F4121
 */
public class ventas extends javax.swing.JInternalFrame {

    private Icon Icon;

    /**
     * Creates new form ventas
     */
    public ventas() {
        initComponents();
        Date fecha1 = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        fecha.setText(sdf.format(fecha1));
    }
    int Saborescontar;
    int Saborespote;
    public void limpiar(){
        nombre.setText("");
        correo.setText("");
        cono.setSelected(false);
        cuarto.setSelected(false);
        medio.setSelected(false);
        kilo.setSelected(false);
        GA.setSelected(false);
        GB.setSelected(false);
        GC.setSelected(false);
        GD.setSelected(false);
        GE.setSelected(false);
        GF.setSelected(false);
        GG.setSelected(false);
        GH.setSelected(false);
        GI.setSelected(false);
    ImageIcon Icon = new ImageIcon("src/imagenes/fin.png");
    }
    public void texto(){
        JOptionPane.showMessageDialog(null, "NOMBRE :"+nombre+"CORREO :"+correo, "Heladeria", HEIGHT, Icon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        correo = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        texto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        GA = new javax.swing.JCheckBox();
        GB = new javax.swing.JCheckBox();
        GC = new javax.swing.JCheckBox();
        GD = new javax.swing.JCheckBox();
        GE = new javax.swing.JCheckBox();
        GF = new javax.swing.JCheckBox();
        GG = new javax.swing.JCheckBox();
        GH = new javax.swing.JCheckBox();
        GI = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cono = new javax.swing.JRadioButton();
        cuarto = new javax.swing.JRadioButton();
        medio = new javax.swing.JRadioButton();
        kilo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        gusto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resetsabores = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();

        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        salir.setText("SALIR");
        salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        limpiar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        limpiar.setText("LIMPIAR");
        limpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        texto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        texto.setText("GENERAR");
        texto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Fecha");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Nombre");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        GA.setText("jCheckBox1");
        GA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAActionPerformed(evt);
            }
        });

        GB.setText("jCheckBox2");
        GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBActionPerformed(evt);
            }
        });

        GC.setText("jCheckBox3");
        GC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCActionPerformed(evt);
            }
        });

        GD.setText("jCheckBox4");
        GD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GDActionPerformed(evt);
            }
        });

        GE.setText("jCheckBox5");
        GE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GEActionPerformed(evt);
            }
        });

        GF.setText("jCheckBox6");
        GF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GFActionPerformed(evt);
            }
        });

        GG.setText("jCheckBox7");
        GG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GGActionPerformed(evt);
            }
        });

        GH.setText("jCheckBox8");
        GH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GHActionPerformed(evt);
            }
        });

        GI.setText("jCheckBox9");
        GI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GIActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("SABORES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(GA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GI, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(GD, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(GG, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(176, 176, 176)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GD)
                    .addComponent(GA)
                    .addComponent(GG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GE)
                    .addComponent(GH))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GC)
                    .addComponent(GF)
                    .addComponent(GI))
                .addGap(18, 18, 18))
        );

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Correo");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cono.setText("CONO");
        cono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conoActionPerformed(evt);
            }
        });

        cuarto.setText("1/4");
        cuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartoActionPerformed(evt);
            }
        });

        medio.setText("1/2");
        medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medioActionPerformed(evt);
            }
        });

        kilo.setText("1 Kilo");
        kilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiloActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Gustos a elegir");

        gusto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cono, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(medio, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cuarto, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(kilo, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(gusto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(101, 101, 101))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuarto)
                    .addComponent(cono))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medio)
                    .addComponent(kilo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gusto))
                .addContainerGap())
        );

        resetsabores.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        resetsabores.setText("VOLVER HABILITAR SABORES");
        resetsabores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetsaboresActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton5.setText("DELIVERY");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fecha.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        fecha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(resetsabores))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                    .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5)
                                    .addComponent(texto)
                                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jButton5))))
                    .addComponent(jLabel1))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(limpiar)
                        .addGap(35, 35, 35)
                        .addComponent(texto)
                        .addGap(32, 32, 32)
                        .addComponent(salir))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(resetsabores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_limpiarActionPerformed

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        texto();
    }//GEN-LAST:event_textoActionPerformed

    private void GAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GAActionPerformed

    private void GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GBActionPerformed

    private void GCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GCActionPerformed

    private void GDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GDActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GDActionPerformed

    private void GEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GEActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GEActionPerformed

    private void GFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GFActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GFActionPerformed

    private void GGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GGActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GGActionPerformed

    private void GHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GHActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GHActionPerformed

    private void GIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GIActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_GIActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        Saborescontar ++;
        if (Saborescontar>=Saborespote){
            GA.setEnabled(false);
            GB.setEnabled(false);
            GC.setEnabled(false);
            GD.setEnabled(false);
            GE.setEnabled(false);
            GF.setEnabled(false);
            GG.setEnabled(false);
            GH.setEnabled(false);
            GI.setEnabled(false);
            JOptionPane.showMessageDialog(null, "No puede elegir mas gustos");
        }
    }//GEN-LAST:event_nombreActionPerformed

    private void conoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conoActionPerformed
        medio.setSelected(false);
        cuarto.setSelected(false);
        kilo.setSelected(false);
        if (cono.isSelected()) {
            Saborespote = 1;
            String cant = Integer.toString(Saborespote);
            gusto.setText(cant);
        }
    }//GEN-LAST:event_conoActionPerformed

    private void cuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartoActionPerformed
        medio.setSelected(false);
        cono.setSelected(false);
        kilo.setSelected(false);
        if (cuarto.isSelected()) {
            Saborespote = 2;
            String cant = Integer.toString(Saborespote);
            gusto.setText(cant);
        }
    }//GEN-LAST:event_cuartoActionPerformed

    private void medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioActionPerformed
        cuarto.setSelected(false);
        kilo.setSelected(false);
        cono.setSelected(false);
        if (medio.isSelected()) {
            Saborespote = 3;
            String cant = Integer.toString(Saborespote);
            gusto.setText(cant);
        }
    }//GEN-LAST:event_medioActionPerformed

    private void kiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiloActionPerformed
        cuarto.setSelected(false);
        cono.setSelected(false);
        medio.setSelected(false);
        if (kilo.isSelected()) {
            Saborespote = 4;
            String cant = Integer.toString(Saborespote);
            gusto.setText(cant);
        }
    }//GEN-LAST:event_kiloActionPerformed

    private void resetsaboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetsaboresActionPerformed
        GA.setEnabled(true);
        GB.setEnabled(true);
        GC.setEnabled(true);
        GD.setEnabled(true);
        GE.setEnabled(true);
        GF.setEnabled(true);
        GG.setEnabled(true);
        GH.setEnabled(true);
        GI.setEnabled(true);
        Saborescontar = 0;
        Saborespote = 0;
        gusto.setText(null);
    }//GEN-LAST:event_resetsaboresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox GA;
    private javax.swing.JCheckBox GB;
    private javax.swing.JCheckBox GC;
    private javax.swing.JCheckBox GD;
    private javax.swing.JCheckBox GE;
    private javax.swing.JCheckBox GF;
    private javax.swing.JCheckBox GG;
    private javax.swing.JCheckBox GH;
    private javax.swing.JCheckBox GI;
    private javax.swing.JRadioButton cono;
    private javax.swing.JTextField correo;
    private javax.swing.JRadioButton cuarto;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel gusto;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton kilo;
    private javax.swing.JButton limpiar;
    private javax.swing.JRadioButton medio;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton resetsabores;
    private javax.swing.JButton salir;
    private javax.swing.JButton texto;
    // End of variables declaration//GEN-END:variables
}
