
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author F4121
 */
public class formularioprestamo extends javax.swing.JInternalFrame {
    
    boolean arroba = false;
    boolean punto = false;
    int paso = 0;
    String mail;
    /**
     * Creates new form formularioprestamo
     */
    public formularioprestamo() {
        initComponents();
    }
public void Crear(){
 
        String archivo = "Prestamo.txt";
        
        String cuit = acuit.getText();
        //String genero = (String) agenero.getSelectedItem();
        String nombre = anombre.getText();
        String apellido = aapellido.getText();
        String fechanac = afechan.getText() ;
        String domicilio = adomicilio.getText();
    
        if(acuit.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Ingrese CUIT - Dato obligatorio");
        }else{
            try {
                try ( //Escribimos el archivo
                        FileWriter escribir = new FileWriter(archivo,true)) {
                    escribir.write(acuit.getText()+ "," + anombre.getText()+ ","
                    + aapellido.getText()+ ","+ afechan.getText()+ ","+ adomicilio.getText()+ ","+ "\r\n");
                }
                
            } catch (IOException ex) {
                System.out.println(ex);
            }
        this.setVisible(false);

        
    }
           }
public void validamail(){
        mail = this.amail.getText();
        
         for (int i = 0; i<mail.length(); i++) {

        for (int j = 0; j<mail.length(); j++) {

            if(mail.charAt(i)=='@' && mail.charAt(j)=='.') {

                arroba = true;
                punto = true;
            }

        }

    }

    if (arroba == true && punto == true) {
        paso = 1;
        System.out.println("Correcto");
        //JOptionPane.showMessageDialog(null, "Correcto");
    }
    else {
        System.out.println("Error!!!");
        JOptionPane.showMessageDialog(null, "Direccion de correo incorrecta");
        }

    }
    
public void limpiar(){
        acuit.setText("");
        agenero.setSelectedIndex(0);
        anombre.setText("");
        aapellido.setText("");
        afechan.setText("");
        adomicilio.setText("");
        alocalidad.setText("");
        aprovincia.setSelectedIndex(0);
        amail.setText("");
        aestado.setSelectedIndex(0);
        ahijos.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adomicilio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        afechan = new javax.swing.JTextField();
        amail = new javax.swing.JTextField();
        aapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        anombre = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        agenero = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        acuit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ahijos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        aestado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        aprovincia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        alocalidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("FORMULARIO PRESTAMO");

        jLabel4.setText("APELLIDO");

        afechan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                afechanKeyTyped(evt);
            }
        });

        jLabel3.setText("NOMBRE");

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        agenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Femenino", "Masculino" }));

        jLabel2.setText("GENERO");

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButton1.setText("CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        acuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                acuitKeyTyped(evt);
            }
        });

        jLabel10.setText("ESTADO CIVIL");

        jLabel1.setText("CUIT/CUIL");

        jLabel9.setText("CORREO ELECTRONICO");

        ahijos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ahijosKeyTyped(evt);
            }
        });

        jLabel8.setText("PROVINCIA");

        aestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Soltero", "Casado" }));

        jLabel7.setText("LOCALIDAD");

        aprovincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Ciudad Autonoma de BA", "Buenos Aires", "Catamarca", "Chaco", "Chubut", "Cordoba", "Corrientes", "Entre Rios", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquen", "Rio Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucuman" }));

        jLabel6.setText("DOMICILIO");

        jLabel5.setText("FECHA DE NACIMIENTO (DD-MM-AAAA)");

        jLabel11.setText("HIJOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anombre)
                            .addComponent(agenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acuit)
                            .addComponent(aapellido)
                            .addComponent(afechan)
                            .addComponent(adomicilio)
                            .addComponent(alocalidad)
                            .addComponent(aprovincia, 0, 400, Short.MAX_VALUE)
                            .addComponent(amail)
                            .addComponent(aestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ahijos))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(acuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(agenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(anombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(afechan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(adomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(alocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(aprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(amail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(aestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ahijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afechanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_afechanKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >=47 && key <= 57;

        if(!numeros){
            evt.consume();
        }
        if(afechan.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_afechanKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        validamail();
        if(paso == 1){
            Crear();
            this.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void acuitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acuitKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >=48 && key <= 57;

        if(!numeros){
            evt.consume();
        }
        if(acuit.getText().length()>=11){
            evt.consume();
        }
    }//GEN-LAST:event_acuitKeyTyped

    private void ahijosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ahijosKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >=48 && key <= 57;

        if(!numeros){
            evt.consume();
        }
        if(ahijos.getText().length()>=1){
            evt.consume();
        }
    }//GEN-LAST:event_ahijosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aapellido;
    private javax.swing.JTextField acuit;
    private javax.swing.JTextField adomicilio;
    private javax.swing.JComboBox<String> aestado;
    private javax.swing.JTextField afechan;
    private javax.swing.JComboBox<String> agenero;
    private javax.swing.JTextField ahijos;
    private javax.swing.JTextField alocalidad;
    private javax.swing.JTextField amail;
    private javax.swing.JTextField anombre;
    private javax.swing.JComboBox<String> aprovincia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
